project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: binder

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  plos-pdf:
    keep-tex: true

execute:
  freeze: auto
