project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links:
    - text: GitHub
      icon: github
      href: https://github.com/mine-cetinkaya-rundel/indo-rct
    - text: Binder
      icon: journal
      href: https://mybinder.org/v2/gh/mine-cetinkaya-rundel/indo-rct/HEAD

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  plos-pdf:
    keep-tex: true

execute:
  freeze: auto
